---
title: Lynnette P. Horner
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
company: Letter Perfect, LLC
email: lynnette@letterperfectllc.com
url: https://letterperfectllc.github.io
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
skills: Copy Editor - Proofreader - Developmental Editor
meta_author: Horner Robert
font:
  primary: Lato, "Helvetica Neue",Helvetica,Arial,sans-serif
  secondary: '"Droid Serif", "Helvetica Neue", Helvetica,Arial,sans-serif'
  header: '"Kaushan Script", cursive'
gems:
- jekyll-sitemap
google_verify: 
bing_verify: 
contact: static
disqus_shortname: myshortname
color:
  primary: 799250
  secondary: 2c3e50
  secondary-dark: 333
  muted: 777
footer:
  copyright: Letter Perfect, LLC
  location: Location
  social: Online
  credits: Credits
social:
- title: twitter
  url: http://twitter.com/jekyllrb
- title: facebook
  url: 
- title: linkedin
  url: http://github.com/jekyll
address:
- line: 8107 S Garfield Way
- line: Centennial, CO 80122
credits: Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start
  Bootstrap</a>.
markdown: kramdown
permalink: pretty
