---
title: Lynnette P. Horner
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
company: Letter Perfect, LLC
email: lynnette@letterperfectllc.com
url: https://letterperfectllc.github.io
description: Letter Perfect copy editing, proofreading, and developmental editing
  by Lynnette P. Horner
meta_author: Horner Robert
gems:
- jekyll-sitemap
color:
  primary: 799250
  secondary: 2c3e50
  secondary-dark: 333
  muted: 777
footer:
  copyright: Letter Perfect, LLC
  location: Location
  social: Online
  credits: Credits
markdown: kramdown
permalink: pretty
baseurl: ''
