- title: Copy Editing and Proofreading
  description: I clean up grammar, punctuation, and spelling errors and will work with you on unclear wording or other issues that require your attention.
  icon: check-square-o
- title: Developmental Editing
  description: I do an extensive analysis of your content and provide scene-by-scene comments, critique, and suggestions for a variety of issues.
  icon: file-text-o
- title: Mentoring and Coaching
  description: I meet with you to discuss your book, including plotting, character development, opening scenes, how to finish, and other elements of the writing craft.
  icon: paper-plane
